version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: your-db
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: your-db
      MYSQL_ROOT_PASSWORD: root
